### ISSUE TITLE
OS error when probing on many files

### ISSUE THREAD

**Issue by sa6656fa-s** [PatrikAAberg/dmce#16]
When trying to probe an OpenJDK version I got a lot of error messages. These error messages was received when trying to probe using dmce-launcher -aq on a directory with many files in it (about 4000 files). This issue could be worked around by increasing the limit of allowed open files, using ulimit -n <nbr files>. Here is a snippet of the error messages received:

Exception in thread Thread-6813:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(self._args, **self._kwargs)
  File "/usr/share/dmce/dmce-copy-headers", line 38, in parse_file
    fp = open(f)
OSError: [Errno 24] Too many open files: '/home/samuel/Documents/MasterThesis/openJDKTest/jdk17/test/hotspot/jtreg/vmTestbase/nsk/jvmti/GetArgumentsSize/argsize001/argsize001.cpp'

Exception in thread Thread-6812:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(self._args, self._kwargs)
  File "/usr/share/dmce/dmce-copy-headers", line 38, in parse_file
    fp = open(f)
OSError: [Errno 24] Too many open files: '/home/samuel/Documents/MasterThesis/openJDKTest/jdk17/test/hotspot/jtreg/vmTestbase/nsk/jvmti/SetLocalVariable/setlocal001/setlocal001.cpp'

Exception in thread Thread-6815:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, self._kwargs)
  File "/usr/share/dmce/dmce-copy-headers", line 38, in parse_file
    fp = open(f)
OSError: [Errno 24] Too many open files: '/home/samuel/Documents/MasterThesis/openJDKTest/jdk17/test/hotspot/jtreg/vmTestbase/nsk/jvmti/GetArgumentsSize/argsize002/argsize002.cpp'

**Comment by PatrikAAberg** [comment]
Big thanks for reporting. This issue should now be solved in a51b2110eed7e4b670c3cccb277f14c6d37404d1
